title: Jekyll:i채 k채ytt채v채 sivusto S2024
description: Tervetuloa sivustolle!
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

header_pages:
- index.md
- vko2.md

github_username: iljuim
